---
dag_id: json2csv_a
start_date: '2024-05-08'
schedule: "*/2 * * * *"
task_configs:
- name: students
  source_path: "/opt/airflow/dags/playground/source/database_a/students"
  columns:
  - id
  - name
  target_file: "/opt/airflow/dags/playground/target/dataset_a/students.csv"
- name: teachers
  source_path: "/opt/airflow/dags/playground/source/database_a/teachers"
  columns:
  - id
  - name
  - start_date
  target_file: "/opt/airflow/dags/playground/target/dataset_a/teachers.csv"
- name: courses
  source_path: "/opt/airflow/dags/playground/source/database_a/courses"
  columns:
  - id
  - name
  - level
  target_file: "/opt/airflow/dags/playground/target/dataset_a/courses.csv"
